replicaCount: 2
project: cocktail

frontend:
  repository:  albionandrew/openshiftcertplay-frontend
  tag: latest
  pullPolicy: Always
  app: cocktailwebfrontend
  servicename: frontendservice

backend:
  repository:  albionandrew/openshiftcertplay-backend
  tag: latest
  pullPolicy: Always
  app: cocktailapi
  servicename: backendservice

nameOverride: ""
fullnameOverride: ""

env:
  - name: ENV
    value: "base"

service:
  port: 8080

labels:
  app: myapp
